# https://docs.github.com/en/actions/use-cases-and-examples/deploying/installing-an-apple-certificate-on-macos-runners-for-xcode-development

name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Should be 3.13
          allow-prereleases: true
      - run: pip install --upgrade pip
      - run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      - run: ./setup.sh
      - run: xcodebuild -workspace Pyto.xcworkspace -scheme Pyto -configuration Release
